name: prompty Python build and test
on:
  pull_request:
    paths:
      - 'runtime/prompty/**'

  workflow_call:


env:
  AZURE_OPENAI_ENDPOINT: https://fake
  AZURE_OPENAI_KEY: 12342323433
  
jobs:
  prompty-tests:
    name: run unit tests on supported python versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        working-directory: ./runtime/prompty
        run: pdm install

      - name: test package
        working-directory: ./runtime/prompty
        run: pdm run pytest

      - name: mypy check
        working-directory: ./runtime/prompty
        run: pdm run mypy . --check-untyped-defs

  publish-artifacts:
    name: publish artifacts
    runs-on: ubuntu-latest
    needs: prompty-tests
    
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.9

      - name: install dependencies
        working-directory: ./runtime/prompty
        run: pdm install

      - name: Publish package distributions to PyPI
        working-directory: ./runtime/prompty
        run: pdm build 

      - uses: actions/upload-artifact@v4
        with:
          name: prompty-artifacts
          path: ./runtime/prompty/dist/*
